### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by bdeelman** [prahaladramji/synology-prometheus#1]
Hi,

I've these error messages, how to resolve them? 

- GF_PATHS_DATA='/var/lib/grafana' is not writable.
- You may have issues with file permissions
- mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied

There is information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later

But I can't figure it out. 

Regards,
Bert

**Comment by xenji** [comment]
Hey. I've hit the same problem. The directory permissions are incorrect. One of the forks has already made a fix for it. SSH into you Synology box and change to the `docker/prometheus` directory.
Then enter:
```
#nobody userid
sudo chown 65534:65534 data/prometheus

#grafana userid
sudo chown 472:472 data/grafana 
```

Reference: https://github.com/ericfortinsp/synology-prometheus/commit/32f15c2dec27d2d7ed094ec88b2ebf5a826676cc#diff-a0f848942ce863cf53c0fa6cc684007dR12

**Comment by prahaladramji** [comment]
Thanks i'll add and update the repo with these permission fixes. Later today.

**Comment by prahaladramji** [comment]
This issue should be fixed by the [latest commit](https://github.com/prahaladramji/synology-prometheus/commit/34ce549c58e44be7373eaefc367a2c2780d61cd1)
